### PR TITLE
Pagination Done

### PR DESCRIPTION
**Pull request by Blastoise**
Pagination for Pokemon Website has been done.

### CODE REVIEW

**Review by BhavyaCodes — APPROVED** [review]

**Comment by BhavyaCodes** [comment]
excellent work, I am merging this PR, but there are a few very tiny changes you can make
1. change the hover effect of the box to cursor
2. disable being able to select text on the pagination button

image

**Comment by Blastoise** [comment]
@Juggernaut9 Sure. It will be done by today.

**Comment by Blastoise** [comment]
Hey @Juggernaut9. Sorry for disturbing you, but can you please label this pull request as hacktoberfest-accept as Hacktoberfest made changes in their rules.

**Comment by Blastoise** [comment]
Or just mark the repo with hacktoberfest topic
https://hacktoberfest.digitalocean.com/hacktoberfest-update
So that nobody's effort goes to waste.

**Pull request merged**
