### PR TITLE
Added Functionality to Search Button

### PR DESCRIPTION
**Pull request by monddelmundo**
This is for #48 

Please review and merge.

### CODE REVIEW

**Comment by BhavyaCodes** [comment]
the search button doesn't work but the search functionality is already on the live website

**Comment by monddelmundo** [comment]
Should it be removed instead?

**Comment by BhavyaCodes** [comment]
Yes you can remove the button, but make the search bar a little bigger @monddelmundo

**Comment by monddelmundo** [comment]
Duly noted on that @Juggernaut9

**Comment by monddelmundo** [comment]
#59 is now for your review

**Pull request closed without merging**
